### ISSUE TITLE
only recent psutil versions have cpu_freq()

### ISSUE THREAD

**Issue by pechfunk** [jflesch/ironscanner#1]
main.py uses psutil.cpu_freq(), which, according to https://stackoverflow.com/questions/42979943/python3-psutils , was added in psutil release 5.2.1. My Ubuntu 17.10 only came with 5.0.1. Should be solvable with a version spec in setup.py, or a try-catch.

**Comment by jflesch** [comment]
Done: 0cf2ca4daf944ca5be98f028e7fe483bf425d5cc :)
